{
  "sudo": "required",
  "language": "c",
  "dist": "trusty",
  "before_script": [
    "sudo apt-get install --no-install-recommends -y build-essential autoconf libtool libssl-dev libpcre3-dev libc-ares-dev libev-dev asciidoc xmlto automake",
    "git submodule update --init --recursive",
    "chmod +x *.sh",
    "./autogen.sh",
    "./configure && make"
  ],
  "script": "sudo make install",
  "group": "stable",
  "os": "linux"
}
