name: Daily Proxies Update
on:
  # Run every 8 hours
  schedule:
    - cron: '0 */8 * * *' 
  # Run when manually triggered
  workflow_dispatch:
jobs:
  update_proxies:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Update Proxies
      # Condition to prevent unintended automatic workflow
      # Change or comment out this line for automatic workflow on forks
      if: github.repository == 'oezeb/cypher-connect'
      run: |
        echo "$(date -u) Updating proxies (cron job)" >> workflow.log
        python3 .github/workflows/update_proxies.py
    - name: Commit and Push
      # Condition to prevent unintended automatic workflow
      # Change or comment out this line for automatic workflow on forks
      if: github.repository == 'oezeb/cypher-connect'
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add .
        git commit -m "Update proxies"
        git push
